name: Build AssisChat IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

     
      - name: Install fastlane
        run: sudo gem install fastlane

      - name: Build unsigned IPA
        run: |
          fastlane gym \
            --project AssisChat.xcodeproj \
            --scheme AssisChat \
            --configuration Release \
            --export_method ad-hoc \
            --skip_codesigning true \
            --output_directory build \
            --output_name AssisChat.ipa

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AssisChat.ipa
          path: build/AssisChat.ipa
